### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by junaid124** [tejeez/rtl_coherent#3]
/tmp/ccRf0o1P.o: In function `dongle_f':
dongles.c:(.text+0x6c): undefined reference to`rtlsdr_set_dithering'
dongles.c:(.text+0x86): undefined reference to `rtlsdr_set_if_freq'
collect2: error: ld returned 1 exit status
make: **\* [main] Error 1

**Comment by andyn** [comment]
Are you using Keenerd's experimental branch of rtl-sdr drivers?

**Comment by junaid124** [comment]
Hi,
Thanks for your time, No i have installed standard drivers, but after having installed said driver i got following errors 
/Downloads/rtl_coherent-master$ ./run.sh ./run.sh: line 1: ./sdl_waterfall: No such file or directory./run.sh: line 2: ./main: No such file or directoryjunaid@junaid:~/Downloads/rtl_coherent-master$ ./crosscorrelate.py Traceback (most recent call last):  File "./crosscorrelate.py", line 14, in <module>    a = np.fromfile(filename, dtype=np.dtype("u1"))IOError: [Errno 2] No such file or directory: 'd00_b'junaid@junaid:~/Downloads/rtl_coherent-master$ ./inter_df.py Traceback (most recent call last):  File "./inter_df.py", line 6, in <module>    import matplotlib.pyplot as pltImportError: No module named 'matplotlib'junaid@junaid:~/Downloads/rtl_coherent-master$ ./plot_covar.py Traceback (most recent call last):  File "./plot_covar.py", line 6, in <module>    import matplotlib.pyplot as pltImportError: No module named 'matplotlib'///////////////////////////////////////////////////////////////////////////////////////////////////////////////after having installed "sudo apt-get install python3-matplotlib"
gui splash up with error 
FileNotFoundError: [Errno 2] No such file or directory: 'fifo'junaid@junaid:~/Downloads/rtl_coherent-master$ ./crosscorrelate.py  music_df.py        run.sh             inter_df.py        plot_covar.py      junaid@junaid:~/Downloads/rtl_coherent-master$ ./crosscorrelate.py Traceback (most recent call last):  File "./crosscorrelate.py", line 14, in <module>    a = np.fromfile(filename, dtype=np.dtype("u1"))IOError: [Errno 2] No such file or directory: 'd00_b'junaid@junaid:~/Downloads/rtl_coherent-master$ ./plot_covar.py Traceback (most recent call last):  File "./plot_covar.py", line 26, in <module>    with open("fifo") as fifo:FileNotFoundError: [Errno 2] No such file or directory: 'fifo'/////////////////////////////////////////////////////////////////////////////////////////////////
Can you please provide the hardware that you have used for this experiment i would like to buy it.   Regards, 
Muhammad Junaid 
Project Manager Tech 
PMD, NRTC, Haripur, Pakistan 
National Radio & Telecom Corporation - Pakistan
Phone (+92)995-666770 | (+92)3335975856  

```
On Monday, May 16, 2016 1:22 PM, Antti <notifications@github.com> wrote:
```

 Are you using Keenerd's experimental branch of rtl-sdr drivers?—

**Comment by andyn** [comment]
Running `make` in the directory should create the fifo in addition to compiling the actual binaries. Edit the config file and change the center frequency to something interesting like around 100 MHz, plug in three rtlsdr devices and run the script. You should either get a grayish or colourful waterfall if the program works. Don't bother editing the array geometry until you have built both an antenna array and the antenna calibration switch board.

A schema will probably be drawn & released in a few weeks. You'll need at least Schmitt triggers to tap the I2C line and solid state RF switches to connect the dongles to a single noise source (the USB data wires work surprisingly well for lower frequencies).

The antenna hardware is mostly made of copper wire, ferrite, PVC pipe, epoxy, aluminum plate and hose clamps. It makes no sense to ship it around the world. ;-)

**Comment by chenhaimeng** [comment]
`root@ubuntu:/home/hmchen/Downloads/rtl_coherent# make
gcc dongles.c main.c synchronize.c correlate.c configuration.c df.c -o main -Wall -Wextra -O3 -lm -ffast-math -lrtlsdr -lpthread -lfftw3f
dongles.c: In function ‘dongle_f’:
dongles.c:46:9: warning: implicit declaration of function ‘rtlsdr_set_dithering’ [-Wimplicit-function-declaration]
  CHECK1(rtlsdr_set_dithering(dev, 0));
         ^
dongles.c:23:16: note: in definition of macro ‘CHECK1’
  int retval = (x); \
                ^
dongles.c:47:9: warning: implicit declaration of function ‘rtlsdr_set_if_freq’ [-Wimplicit-function-declaration]
  CHECK1(rtlsdr_set_if_freq(dev, conf.if_freq));
         ^
dongles.c:23:16: note: in definition of macro ‘CHECK1’
  int retval = (x); \
                ^
/tmp/cczi2yRh.o: In function `dongle_f':
dongles.c:(.text+0x7a): undefined reference to `rtlsdr_set_dithering'
dongles.c:(.text+0x94): undefined reference to `rtlsdr_set_if_freq'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'main' failed
make: *** [main] Error 1
root@ubuntu:/home/hmchen/Downloads/rtl_coherent# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            465M     0  465M   0% /dev
tmpfs            98M  7.4M   90M   8% /run
/dev/sda1        19G  5.2G   13G  30% /
tmpfs           486M  312K  486M   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           486M     0  486M   0% /sys/fs/cgroup
tmpfs            98M   88K   98M   1% /run/user/1000
root@ubuntu:/home/hmchen/Downloads/rtl_coherent#`

**Comment by andyn** [comment]
Again, install [Keenerd's experimental branch](https://github.com/keenerd/rtl-sdr) drivers and recompile.

The amount of disk space has nothing to do with this issue whatsoever. If you're having other problems, post a new bug report.

**Comment by chenhaimeng** [comment]
step：
1：clone https://github.com/keenerd/rtl-sdr.git
  cd rtl-sdr
  mkdir build
  cd build
  cmake ..
  make
  sudo make install
  sudo ldconfig

2：clone  https://github.com/tejeez/rtl_coherent.git
  make
dongles.c:(.text+0x7a): undefined reference to rtlsdr_set_dithering' dongles.c:(.text+0x94): undefined reference tortlsdr_set_if_freq'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'main' failed
make: *** [main] Error 1

**Comment by gaussian-curve** [comment]
Has anyone found a solution to this problem yet? I'm also experiencing this problem despite installing keenerd and tejeez's repos.

`odroid@odroid:~/Downloads/rtl_coherent$ make
gcc dongles.c main.c synchronize.c correlate.c configuration.c df.c -o main -Wall -Wextra -O3 -lm -ffast-math -lrtlsdr -lpthread -lfftw3f
/tmp/cccDDRG3.o: In function `dongle_f':
dongles.c:(.text+0x6a): undefined reference to `rtlsdr_set_dithering'
dongles.c:(.text+0x78): undefined reference to `rtlsdr_set_if_freq'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'main' failed
make: *** [main] Error 1
`

**Comment by tejeez** [comment]
Maybe you still have some other version of librtlsdr installed in another path. Things you could check and try:
- Did you remember to run `ldconfig` after installing rtl-sdr?
- Try `whereis librtlsdr` and see if it gives the path where you installed it (usually /usr/local/lib/librtlsdr.so by default).
- `export LD_LIBRARY_PATH=/usr/local/lib` before compiling and running rtl_coherent might help but is usually not needed.
- If you've installed rtl-sdr from your package manager, uninstall it if possible. This is not usually necessary though and might also uninstall some other programs that depend on it.
